version: 1.0
jobs:
  build_test:
    docker:
      - image: circleci/node:22
    steps:
      - checkout
      - run:
          name: Install npm dependencies
          command: |
            npm install --save	
  build_docker_image:
    docker:
      - image: circleci/node:22
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: false
      - run:
          name: Build Docker image
          command: |
            docker build -t demo_nodejs_webpage -t sourav673/demo_nodejs_webpage7 .
            echo $DOCKER_PASSWORD | docker login -u sourav673 --password-stdin
            docker push sourav673/demo_nodejs_webpage7:latest

workflows:
  build_test:
    jobs:
      - build_test
      - build_docker_image



